### ISSUE TITLE
Files not found in Visual Studio

### ISSUE THREAD

**Issue by Quantentunnel** [ChaosEmerald95/ExplorerPlus#1]
Maybe i am doing something wrong but after downloading the project from github i opened the project in VS and get the following error messages:

```
Application.Designer.vb not found
AssemblyInfo.vb  not found
Resources.Designer.vb not found
Settings.Designer.vb  not found
```

I guess "ExplorerPlus" is the start project. So i chance that but got new error messages. I think they appear because of the missing files i listed up above. For example, the StringResource reference can not be found.

Can you please upload the missing files? Thanks!

**Comment by ChaosEmerald95** [comment]
Thanks for reporting the issue. I will fix it in the .gitignore.

**Comment by ChaosEmerald95** [comment]
All missing files are now uploaded

**Comment by Quantentunnel** [comment]
Thank you!
I will now try to open it with the newst version.
