### ISSUE TITLE
SyntaxErrors

### ISSUE THREAD

**Issue by Quantentunnel** [ChaosEmerald95/ExplorerPlus#2]
There are several syntax errors. When i delete the characters "?" in the code, then i can compile the project. 
For instance one syntax error is in line 273 of ExplorerPlusFileView.cs

**Comment by ChaosEmerald95** [comment]
The "?" before the invoke-Commands is a feature of C# 6.0 . You must compile the project with Microsoft Visual Studio 2015.
I will fix the syntax error in the next 2 days, because i haven't actually not much time.
