### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by Quantentunnel** [ChaosEmerald95/ExplorerPlus#3]
I get aNullReferenceException in line 220 of ExplorerPlusFileView.cs
 --> LoadedPath.Invoke(_selectedpath);

**Comment by ChaosEmerald95** [comment]
When you don't have a ? before the Point, than you have a Exception. Like in in Issue #2 you need C# 6.0 and you must compile it with visual Studio 2015

**Comment by Quantentunnel** [comment]
Ok i understand. I have VS 2013. :-)
